language: csharp
solution: plivo.sln

matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      dist: trusty
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
      install:
        - dotnet build --framework netcoreapp1.1 plivo-dotnet.csproj
      script:
        - dotnet run --framework netcoreapp1.1 plivo-dotnet.csproj
    - mono: latest
